go-vela/ui

.env.example, src/static/index.ts
Updated to match the server environment variable of [VELA_SOURCE_URL](https://github.com/go-vela/server/blob/38116bdb7c7ad1c8b299ed954f4d383ae663f118/cmd/server/main.go#L147).
=> fix(variable): use consistent variable across server and ui

src/elm/Build.elm
=> Hotfix: adding aria labels to build history links

.github/workflows/ci.yml
this was an accidental commit: https://github.com/go-vela/ui/commit/6ebfdc808ee34002e8641ce480f6e8905d9d33f7
😶
=> revert(ci): revert reversal of previous change

src/elm/Alerts.elm, src/scss/_main.scss
=> fix(style): adding themed font color to alerts

.github/workflows/ci.yml, .github/workflows/publish.yml, .github/workflows/release.yml, package-lock.json, package.json
update dependencies and deal with issue mentioned in https://github.com/cypress-io/github-action#important which causes cypress to fail. updated all ubuntu images for consistency.
=> chore(deps): update dependencies

src/elm/Main.elm, src/scss/_main.scss
we got dinged for this in the a11y test (https://dequeuniversity.com/rules/axe/3.4/region?application=axeAPI)
it will still fail in dev/ci, because of the Elm debug dialog in the bottom right corner, but we'll pass with the production bundle.
=> refactor(html): ensure content is in landmarks

cypress/integration/settings.spec.js, package-lock.json, src/elm/Api.elm, src/elm/Api/Endpoint.elm, src/elm/Main.elm, src/elm/Pages/Settings.elm, src/elm/Vela.elm, src/scss/_settings.scss
Add chown and repair functions to settings page:
closes #93
=> feat(settings): add chown/repair actions

cypress/integration/settings.spec.js, src/elm/Alerts.elm, src/elm/Help/Help.elm, src/elm/Main.elm, src/elm/Pages/Settings.elm, src/elm/Vela.elm, src/scss/_main.scss
adds the following to the settings page:
=> feat(settings): add status badge section

nginx/default.conf, nginx/local.conf
Allow CLI to use web UI URL for things beyond login
=> enhancement(proxy): allow more CLI requests to hit backend

docker-compose.yml
extension of #137 
minor difference in the container name
=> fix(infra): updating server name to reflect minor difference in UI vs server

src/elm/Main.elm
I missed a commit somehow that included the pager update in Main.elm. my mistake!
=> fix(secrets): pagination buttons

src/elm/Help/Commands.elm
Noticed this when clicking one of the 'upvote feature' button in the CLI thing in the top right corner.
=> fix: correct issue base URL

src/elm/Help/Commands.elm
Based off of https://github.com/go-vela/docs/pull/143 and https://github.com/go-vela/cli/pull/140
* updated the `engine` flag to `secret.engine`
* updated the `type` flag to `secret.type`
=> refactor: update engine to secret.engine and type to secret.type

src/elm/Main.elm, src/elm/Util.elm
focus was being set, but page was not auto scrolling when using log line range
=> fix(logs): fix bug when visiting page with log range

cypress/integration/steps.spec.js, src/elm/Logs.elm, src/scss/_main.scss, src/scss/_themes.scss
Match text with skip icon previously introduced.
=> enhance(skip): change kill to skip

src/elm/Pages/Build/View.elm, src/scss/_main.scss
fix for pull #225 
simple style tweak
=> fix(build): fixing tooltip style

src/elm/Main.elm, src/elm/Search.elm
piggy back off #231 and extends the functionality to `/account/source-repos`
Kudos to @bmuenzenmeyer  for the idea
=> enhance(source): focus on source repos search bar

src/elm/Pages/Build/View.elm, src/scss/_main.scss
pulling out of changes made in #237 
no functional updates, just cleaner code
=> fix(html): simplify logs header code

src/elm/Api.elm, src/elm/Api/Endpoint.elm, src/elm/Vela.elm
adding services to Api.elm, in preparation for https://github.com/go-vela/community/issues/166
=> feat(services): adding services to Api endpoints

src/elm/SvgBuilder.elm
unused, unimpactful, but fixes pesky errors that have been there for awhile.
=> fix(svg): removing bad svg attributes

src/elm/Focus.elm, src/elm/Main.elm, src/elm/Pages/Build/Logs.elm, src/elm/Pages/Build/Update.elm, src/elm/Pages/Build/View.elm, src/elm/Vela.elm
prep work for go-vela/community#166
no functional changes, but modularizes log helper functions using a new Resource type in Vela.elm
prepares for the introduction of services
=> feat(nav): modularize logs, prep work

.github/renovate.json
ran `npm run lint:fix`
fixes broken linting on `master` introduced by #260
=> fix(lint): lint renovate.json

src/elm/Pages/Hooks.elm, src/scss/_table.scss, src/scss/_themes.scss
closes https://github.com/go-vela/community/issues/186
=> fix: error rendering on hooks page

src/elm/Pages/Hooks.elm
=> fix(audit): adding ansi decode to audit errors

src/elm/Help/Commands.elm, src/elm/Help/View.elm, src/elm/Main.elm
fixing links, updating some CLI commands that have since been implemented (hooks, services)
=> fix(docs): updating CLI help and fixing docs links

nginx/default.conf, nginx/local.conf
tl;dr - don't allow framing of the site; only allow form submissions to itself.
=> fix(csp): explicitly set missing directives

src/elm/Pages/Build/View.elm
fixes style regression introduced by stages by grouping init and clone into a single stage
=> fix(css): fix stages style regression

caddy/Caddyfile, caddy/Caddyfile.local, docker-compose.yml
logs didn't get scrubbed properly with previous config. this should do it.
=> fix(caddy): remove sensitive logs

src/elm/Main.elm, src/elm/Pages/Build/View.elm, src/elm/Vela.elm
fixes: https://github.com/go-vela/community/issues/208
=> fix: stop UI duration timer when build is in a final state

.env.example, docker-compose.yml
Related to https://github.com/go-vela/server/pull/333, https://github.com/go-vela/server/pull/336 and https://github.com/go-vela/worker/pull/178
This updates the environment variables to reflect the changes above.
Also took the opportunity to add an environment variable that was a part of previous changes for the server:
* `VELA_DATABASE_ENCRYPTION_KEY`
=> chore: update environment variables for services

DOCS.md
Updates docs to be correct after https://github.com/go-vela/server/pull/333
=> docs: update local dev docs

src/elm/Pages/Deployments/View.elm
=> fix: deployments svg class crash

package-lock.json
bumps 3 packages due to security updates. just ran `npm audit fix`
=> chore(deps): upgrade deps with security fixes

.env.example, DOCS.md, docker-compose.yml
Related to https://github.com/go-vela/server/pull/594 and https://github.com/go-vela/worker/pull/275
This updates some the local documentation to reflect the current state of the project.
Also syncing some of the local setup between the core components:
* ui
* server
* worker
=> refactor: docs for local setup

src/elm/Main.elm, src/elm/Pages/Pipeline/View.elm
fixes the download link for the revised pipeline tab.
the button was pulling from decodedData that was never being updated in the model.
=> fix: pipeline download link

cypress/integration/pipeline.spec.js, src/elm/Pages/Pipeline/View.elm
closes https://github.com/go-vela/community/issues/775
=> enhance(pipeline): render expansion toggle regardless of templates

src/elm/Pages/Build/View.elm, src/elm/Util.elm
see title
closes https://github.com/go-vela/community/issues/598
=> fix(deployments): point commit link to clone/tree/ref instead of api deployment

cypress/integration/pipeline.spec.js, src/elm/Pages/Pipeline/View.elm, src/scss/_pipelines.scss
followup/cleanup from the changes made in #639
=> fix: remove template wording from pipeline expansion

package-lock.json, package.json
includes:
- https://github.com/go-vela/ui/pull/650
- https://github.com/go-vela/ui/pull/638
- https://github.com/go-vela/ui/pull/636
=> chore(deps): cumulative upgrade

src/elm/Help/Commands.elm, src/elm/Main.elm
reverts some changes made in #660
=> refactor: revert import format

src/elm/Main.elm, src/elm/Pages/Schedules/Model.elm, src/elm/Pages/Schedules/Update.elm, src/elm/Pages/Schedules/View.elm, src/elm/Vela.elm
also removing unused fields from the model that already exist in the form, like `id` `entry` and `enabled`
=> enhance: add more fields to schedules table

cypress/integration/schedule.spec.js, src/elm/Main.elm, src/elm/Pages/Schedules/Form.elm, src/elm/Pages/Schedules/Model.elm, src/elm/Pages/Schedules/View.elm, src/elm/Util.elm, src/scss/_main.scss
- enhance: add utc time warnings to schedules forms
- enhance: add utc time.now view to schedule forms
- refactor: move forms code to `Schedules/Form.elm` and fill out missing comments
=> enhance(schedules): add utc warning 

docker-compose.yml
adding the env variables introduced by https://github.com/go-vela/server/pull/843 also depends on https://github.com/go-vela/server/pull/939 but this can be merged whenever.
=> chore(compose): adding queue signing keys

cypress/integration/secrets.spec.js, src/elm/Main.elm, src/elm/Pages/Secrets/Form.elm, src/elm/Pages/Secrets/Model.elm, src/elm/Pages/Secrets/View.elm
Part of effort for https://github.com/go-vela/community/issues/851.
Also see https://github.com/go-vela/types/pull/308
=> fix(secrets): add schedule to form for secrets if repo is on allowlist

cypress/fixtures/hooks_5.json, cypress/integration/hooks.spec.js, src/elm/Pages/Hooks.elm, src/elm/SvgBuilder.elm, src/scss/_table.scss
Ref: https://github.com/go-vela/server/pull/993
=> enhance(audit): parse skipped webhooks and show messaging

cypress/fixtures/repositories.json, cypress/fixtures/repositories_100.json, cypress/fixtures/repositories_10a.json, cypress/fixtures/repositories_10b.json, cypress/fixtures/repositories_5.json, cypress/fixtures/repository.json, cypress/fixtures/repository_inactive.json, cypress/fixtures/repository_updated.json, cypress/fixtures/secret_org.json, cypress/fixtures/secret_repo.json, cypress/fixtures/secret_shared.json, cypress/fixtures/secrets_org_5.json, elm.json, src/elm/Pages/RepoSettings.elm, src/elm/Pages/Secrets/Form.elm, src/elm/Pages/Secrets/Update.elm, src/elm/Pages/Secrets/View.elm, src/elm/Vela.elm
Request for Vela to process and create builds for pull request [labeled](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=labeled#pull_request) and [unlabeled](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=unlabeled#pull_request) webhooks.
GitHub [issue #913](https://github.com/go-vela/community/issues/913)
GitHub [ideas #768](https://git.target.com/orgs/vela/projects/36/views/1?filterQuery=win+san&pane=issue&itemId=19205)
=> feat(rulesets): add support for PR labeled events

src/elm/Api/Operations.elm, src/elm/Components/Favorites.elm, src/elm/Pages/Account/SourceRepos.elm, src/elm/Shared/Model.elm, src/elm/Shared/Msg.elm, src/elm/Utils/Favorites.elm, src/elm/Vela.elm
see: https://github.com/go-vela/server/pull/1095
=> refactor: nested api objects, repository

src/elm/Auth/Jwt.elm
missed change here
https://github.com/go-vela/server/pull/1113
=> fix: set is_admin claim to optional

src/elm/Pages/Dash/Secrets/Engine_/Org/Org_/Name_.elm, src/elm/Pages/Dash/Secrets/Engine_/Repo/Org_/Repo_/Name_.elm, src/elm/Pages/Dash/Secrets/Engine_/Shared/Org_/Team_/Name_.elm
closes https://github.com/go-vela/community/issues/1001
=> fix(secrets): clear form on update

elm.json, package-lock.json
ran `npx elm-json upgrade` to upgrade elm deps and `npx update-browserslist-db@latest` to update browserlist database
=> chore: update elm deps + browserlist

elm.json, package-lock.json
ran `npx update-browserslist-db@latest` and `npx elm-json upgrade`
=> chore(deps): elm packages + browserlist

cypress/integration/deployment.spec.js, src/elm/Pages/Org_/Repo_/Deployments/Add.elm, src/elm/Utils/Helpers.elm
parameter format of key=valuekey=value was not supported on redeploy action
=> fix(deployment): support parameter value containing equal sign on redeploy

cypress/fixtures/build_approved.json, cypress/fixtures/build_canceled.json, cypress/fixtures/build_error.json, cypress/fixtures/build_failure.json, cypress/fixtures/build_graph.json, cypress/fixtures/build_pending.json, cypress/fixtures/build_pending_approval.json, cypress/fixtures/build_running.json, cypress/fixtures/build_success.json, cypress/fixtures/builds_10a.json, cypress/fixtures/builds_10b.json, cypress/fixtures/builds_5.json, cypress/fixtures/builds_50.json, cypress/fixtures/builds_all.json, cypress/fixtures/builds_comment.json, cypress/fixtures/builds_pull.json, cypress/fixtures/builds_push.json, cypress/fixtures/builds_schedule.json, cypress/fixtures/builds_tag.json, cypress/fixtures/settings.json, cypress/fixtures/settings_updated.json, cypress/integration/admin_settings.spec.js, cypress/integration/build.spec.js, src/elm/Components/RecentBuilds.elm, src/elm/Pages/Admin/Settings.elm, src/elm/Vela.elm, tests/BuildMetricsTest.elm
Follow up from https://github.com/go-vela/server/pull/1320
=> enhance: add queue restart limit to admin settings and route to build tooltip

src/elm/Pages/Admin/Settings.elm
=> fix(admin): use accurate description for queue restart limit
