Makefile
prior to this we deleted node_modules first and then ran an npm script that executes something that resides in one of the deleted folders 🐛
=> build(make): change order of clean cmds

src/elm/Logs.elm, src/elm/Main.elm, src/elm/Pages/AddRepos.elm, src/elm/Pages/Build.elm, src/elm/Pages/Hooks.elm
Added lazy rendering to all pages.
https://guide.elm-lang.org/optimization/lazy.html
When wrapped in Html.lazyN, Elm will check the input used for the last frame render and compare it to the input for the current frame render. If the input and function have not changed, then the virtual DOM doesnt need to be updated and Elm will ignore that frame.
Best when used at the root of the application where the model is parsed and used as view input, so I added it to the Pages controller.
=> perf(html): lazy node rendering for pages root

src/scss/_main.scss
=> fix(history): removing sticky tooltip overlap

src/elm/Pages/Home.elm
=> fix(home): use full name for filtered repos

src/elm/Alerts.elm
adding bounceInRight and fadeOutRightBig to the comments will stop these override classes from being scrubbed by our production build minification process
=> fix(alerts): add override animation classes to config comments

.env.example, .github/DOCS.md, .github/workflows/ci.yml, docker-compose.yml, docker-entrypoint.sh, src/elm/Api/Endpoint.elm, src/elm/Main.elm, src/elm/Main/index.d.ts, src/static/index.ts
- removes SCM information from UI and utilizes server for initiating auth flow
- UI will no longer need `VELA_SOURCE_URL` and `VELA_SOURCE_CLIENT` env vars
=> fix(login): utilize server for login

cypress/fixtures/add_repo_response.json, cypress/fixtures/repositories.json, cypress/fixtures/repositories_100.json, cypress/fixtures/repositories_5.json, cypress/fixtures/repository.json, cypress/fixtures/repository_updated.json, cypress/fixtures/source_repos.json, docker-compose.yml, src/elm/Pages/RepoSettings.elm, src/elm/Vela.elm
Added the new ruleset `comment` functionality into the repo settings page.
This will allow a user to enable comment events on the repository so they can write `steps:` that utilize the new ruleset functionality.
=> feat: add repo comment event to settings page

.github/workflows/publish.yml
this should fix an issue with the original package we used github.com/itchio/gothub that suddenly started throwing errors. we moved back to the original repo that itchio forked since it looks like it has found new maintainers.
=> ci: fix depedency

nginx/default.conf, nginx/local.conf
this fixes issue with CLI not able to login due to trailing `/` in location, for example
=> fix(nginx): correct pathing for location

src/elm/Pages/Secrets/Form.elm
Adding the comment event so people can scope their secrets to the comments functionality added in `v0.4.0`
https://go-vela.github.io/docs/usage/pipeline/steps/ruleset/#comment
=> enhancement(secrets): add comment event

src/elm/Help/Commands.elm
Ran into an issue copying and pasting the command `vela view step --org foo --repo bar --build x --step x`
Changed to be step-number. Let me know if I missed something :D
=> fix(help): --step in help window should be --step-number

src/elm/Pages/Builds.elm
I noticed this typo after I added a new repository today.
My guess is the word `repository` was intended instead of `respository`.
=> Fix typo in Builds.elm

cypress/integration/build.spec.js, cypress/integration/builds.spec.js, src/elm/Pages/Build.elm, src/scss/_main.scss
Moving commit message next to build number due to element stretching with error message. This keeps the element compact and consistent. Old version also had an issue with time info disappearing for long commit messages. Evidence below taking from Cypress tests for the element in an error state.
=> fix(message): move msg next to build number

src/scss/_main.scss
recent change updated this class, forgot to propagate the change to remove it from the last step
=> fix(css): remove partial flowline from last build step

.postcssrc.js, src/scss/_ansi.scss
ansi styles are applied during runtime, therefore purgecss is considering the ansi stylesheet as "unused" and is consequently scrubbing it from the production parcel build.
this commit adds ignore flags to _ansi.scss
=> fix(css): ignore ansi stylesheet during purgecss

src/elm/Main.elm, src/elm/Pages/Build/Logs.elm, src/elm/Pages/Build/View.elm, src/elm/Util.elm, src/elm/Vela.elm
preparing for future log updates, moving base64 decode to when log is received, rather than on view/render.
this should improve performance greatly and goes in hand with additional incoming enhancements
=> perf(logs): moving base64 decode to log receiver

cypress/integration/steps.spec.js
fixing > https://github.com/go-vela/ui/runs/1151230679#step:8:883
```
CypressError: `cy.type()` failed because it requires a valid typeable element.
```
=> fix(tests): update cypress test to fix type(shift) by attaching it to an input

package-lock.json
bumping `node-forge` to `^0.10.0`
solves Prototype Pollution vulnerability 
https://github.com/advisories/GHSA-92xj-mqp7-vmcj
=> chore(deps): updating vulnerable dependency

elm.json, src/elm/Main.elm, src/elm/Pages/Build/Logs.elm, src/elm/Util.elm, src/elm/Vela.elm
optimizing base64 decode process a bit with some small tweaks:
- update to use more performant base64 library (javascript solution still WIP)
- use updateIf rather than setIf when overwriting logs
- only base64 decode when we actually update the logs in the model
saw several performance improvements
large-logs performance bottleneck has been more-or-less transferred to table/row renderanimationframe bloating
=> perf(logs): optimization, only base64 decode when logs change

cypress/integration/logs.spec.js, src/elm/Pages/Build/View.elm, src/scss/_main.scss
3 changes
- refactor existing logs style, cleaner structure, removed redundant css
- made step skipped/errors more readable, moved red font to error label only
- added a message for empty logs and empty error (null)
=> enhance(logs): refactor and clean up logs controller and style

src/elm/Pages/Build/View.elm, src/scss/_main.scss
Adding 
```css
word-break: break-word;
```
to fix a bug with single-word logs that extend past the screens viewport.
=> fix(css): adding break-word to logs

src/scss/_main.scss, src/scss/_themes.scss, src/scss/_variables.scss
Fixing the flowline color. In #216 the hardcoded color was removed but using `var(--color-bg-light)` is more difficult to see. This change adds a better gray for light/dark theme and uses it for the flowline.
See below.
*After* is almost identical to the hardcoded color in the current release (0.7.0)
=> fix(css): adding gray color var to match current release flowline color

src/elm/Pages/Build/View.elm, src/scss/_main.scss
* Indented `Recent Builds` will be inline with the default selected most recent build in the build history
=> feat(build): add recent builds title

DOCS.md, docker-compose.yml, package.json, secrets.env.example
with the changes introduced in #226 we now have to pass in `VELA_API` manually if you want to run local dev via `npm run dev`. This PR will override the standard location that `parcel` uses (`.env`) to use the newly added `secrets.env` file. So, as long as you define `VELA_API` in `secrets.env` as we did previously with `.env`, you will not need to pass it manually.
=> chore: use secrets.env

src/elm/Pages/RepoSettings.elm
* Minimum build timeout has been lowered from 30 minutes to 1 minute; the default for newly enabled repos is still 30 minutes.
* Dependent on pr: https://github.com/go-vela/types/pull/119
=> feat(repo settings): allow minimum build timeout of 1 minute

src/scss/_main.scss
set display inline to the Recent Builds title <p>
didnt notice this when merging that one in
=> fix(css): fix small recent builds css regression

src/scss/_main.scss
better fix for:
https://github.com/go-vela/ui/pull/218
did not formerly account for infinite "......" that do not break in display: table.
now breaks text properly.
=> safe fix for breaking long lines

src/elm/Nav.elm, src/elm/Pages/Build/View.elm, src/elm/Util.elm
prep work for https://github.com/go-vela/community/issues/166
no functional changes, but fixes an inevitable cyclical import issue
moving buildhistory and some util functions so they may be used across multiple pages
=> feat(nav): move code, prep work

src/elm/Api.elm, src/elm/Main.elm, src/elm/Pages/Pipeline/Api.elm, src/elm/Pages/Pipeline/Model.elm, src/elm/Pages/Pipeline/Update.elm, src/elm/Pages/Pipeline/View.elm, src/elm/Vela.elm, src/scss/_pipelines.scss
prep work for go-vela/community#166
some changes here can be found in the open PRs: #252 #253
- adds a PipelineTemplates type for more easily tracking pipeline templates in the Model.
- adds a "Download vela.yml" button to Pipelines
=> feat(nav): adding pipeline types and download yml button, prep work

src/elm/Main.elm, src/elm/Pages/Build/Logs.elm, src/elm/Pages/Build/Model.elm, src/elm/Pages/Build/Update.elm, src/elm/Pages/Build/View.elm, src/elm/Vela.elm
prep work for go-vela/community#166
some changes here can be found in the open PRs: #252 #253
*No functional changes* 
- adds a StepsModel for tracking steps information which will be more obvious when introducing services
- changes steps to resources so the code may be used for services
- moves the updated code out of Update.elm so that file may be deleted in the following PR
=> refactor(steps): adding StepsModel and moving code from Update.elm, prep work

docker-compose.yml, src/elm/Nav.elm
this fixes a scenario where an invalid org/repo is provided.
using org/name in the repoModel depends on a successful build, so this is a bug
for example, if I visit a repo that has a valid org but bad repo, we should still see org secrets at 
vela.com/-/secrets/native/repo/DavidVader/dd
this fixes that
=> fix(nav): use page input for repo tabs

docker-compose.yml
updates the docker-compose.yml to match the flags that were changed in  https://github.com/go-vela/server/pull/236 and https://github.com/go-vela/worker/pull/130
=> chore: update docker-compose to match updated server and worker

src/elm/Pages/Home.elm, src/scss/_main.scss, src/scss/_nav.scss
giving source repos and home page filter bar some breathing room
=> fix(css): adding margin to search bars

src/elm/Main.elm, src/elm/Pages/Settings.elm
quick addition that will show time remaining on token:
=> feat(settings): show time remaining on token

package-lock.json, package.json
purgecss v4 causes issues atm similar to the autoprefixer upgrade.  will need to address separately.
=> revert: purgecss upgrade from #293

src/scss/_nav.scss
gives another visual cue on hovering tabs. will also show when in focus.
not excited about targeting `a` tag directly. i think with a different implementation we can avoid the the "costly" animation as the linter points out as well.
=> enhance(tabs): show bottom line on hover

src/elm/Nav.elm, src/scss/_nav.scss
closes https://github.com/go-vela/community/issues/191
Likely not the final form of this feature. Enough for MVP, probably.
One note: audit doesn't refresh unless it's the active tab, so you only see it on page load. It does disappear when a new build successfully starts (when you are on the builds tab) because it invalidates the condition by which the "alert" is added.
I lied, two notes: No tests (yet; hence draft status)
=> feat: add visual alert for audit

src/elm/Api.elm, src/elm/Crumbs.elm
Fixes issue primarily present in secrets where the last crumb is a link. The updated crumb design doesn't really accommodate that use. There's probably a couple of ways this could be fixed - this is one suggestion, adding "Add" as the last crumb when you are on a page to add a secret.
To consider.. changing "Add" to "Add Secret" or "Add Repo Secret"/"Add Org Secret".. that might eliminate the need for the heading on those pages, ie. "Add Repo Secret". Or, more invasively.. in the example's case, change "services" to "services Secrets" and keeping it as "Add", etc.
=> fix(crumbs): change last segment to not be a link

docker-compose.yml, nginx/default.conf, nginx/local.conf
this proposes a potential fix for `invalid URL prefix error` and the Caddy v2 infinite redirect loop issue
```
2021/02/09 18:40:28 [error] 11#11: *7 invalid URL prefix in "/authenticate?redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fauthenticate%2Fcli%2F53958" while sending to client, client: 172.30.0.1, server: vela, request: "GET /login?port=53958&type=cli HTTP/1.1", host: "localhost:8888"
```
requires revert of https://github.com/go-vela/ui/pull/316 from caddy back to nginx
=> fix: revert caddy, add host/scheme prefix to redirect proxy

src/elm/Api.elm, src/elm/Main.elm
updating to match
https://github.com/go-vela/worker/pull/152
non-breaking but fixes ugly alert and uses canceled build to update the build if the user is actively viewing it
=> fix(api): update cancel response to build

src/elm/Main.elm
do not pre-load secrets unless visiting the tab explicitly
fixes: https://github.com/go-vela/community/issues/206
=> fix(repo): fixes error for non admin repo visitors

src/elm/Nav.elm
the cancel button only renders on the build steps tab.
this fix adds the button to the pipeline and services tabs.
=> fix(cancel): add cancel button to all build resources

.github/renovate.json
Tweaking renovate config to avoid getting PRs for "nightly" releases. We did it once to get away from Parcel 1 and have since switched to the beta branch. Will try to stay there until next beta and/or full release of Parcel 2.
=> chore: tweak renovate

Dockerfile
Pinning to specific version of the nginx image and with that updating from Nginx `1.18.0` to `1.19.1` to be on latest.
This should mitigate: https://vuldb.com/?id.155282#:~:text=NGINX%20through%201.18.,since%2004%2F28%2F2020
=> chore: bump nginx to 1.19.1

.github/renovate.json
ok, different approach to ignore `nightly` package PRs. see the following for references:
- https://docs.renovatebot.com/configuration-options/#matchpackagepatterns
- https://docs.renovatebot.com/configuration-options/#allowedversions
=> chore(renovate): tweak config .. one more time

docker-compose.yml, src/elm/Pages/Build/History.elm, src/scss/_main.scss
worker names are getting longer, right align tooltip fields
=> fix: right align long tooltip fields

src/elm/Pages/Build/History.elm, src/elm/Util.elm
closes https://github.com/go-vela/community/issues/244
=> fix: adding default for 0 timestamps in tooltip

src/elm/Main.elm, src/elm/Pages/SourceRepos.elm
PR Includes the following changes:
* Update spelling from `Github` to `GitHub` on auth page
* Update spelling from `Github` to `GitHub` on source repos page
_Note: updating for consistency and to correct GitHub proper capitalization_
=> fix: update github spelling

src/scss/_forms.scss
fixes an issue with form label overflowing onto buttons making the buttons less accessible, kinda like..
```
+----form-control------+ +----<button>----+
| +-----------+ +------|-|----------------|---+
| |  <input>  | |        <label>          |   |
| +-----------+ +------|-|----------------|---+
+----------------------+ +----------------+
```
(not scaled to size)
it only allowed interactivity at the top and bottom of the button. 
the issue was observed in Firefox v89 on the Repo Settings page, specifically the Build Timeout setting.
=> fix(form): fix overlap in non-stack scenario

docker-compose.yml
Related to https://github.com/go-vela/server/pull/418
This fixes the database configuration variables for the `server` service in the Docker compose file.
=> fix(compose): database config for server

src/elm/Pages/Secrets/Form.elm, src/elm/Pages/Secrets/Update.elm, src/elm/Pages/Secrets/View.elm
Related Issue: https://github.com/go-vela/community/issues/87
Added radio to select if secret should be allowed in commands.
Interestingly I found most of this code in another commit: https://github.com/go-vela/ui/commit/ea4e8056f40ee537c152add529d45d4ead22a931#diff-ebc97117a8ca6bd59c6e215aef88e99ca9daef03682fbab29858ece410e754c3R237-R256
The code from the commit above only worked for update, not for adding a secret. I was able to tweak it to work in both scenarios.
=> feat: add allow_command radio buttons to Secrets UI

src/elm/Main.elm
closes [#358](https://github.com/go-vela/community/issues/358)
Example: (`MatthewFevold` is my org)
=> fix: changes org page title to org name - Vela

.github/workflows/ci.yml, .github/workflows/publish.yml, .github/workflows/release.yml
Seems that using `ubuntu-16.04` is not supported anymore. It was pinned previously due to issues with Cypress. Attempting to use `ubuntu-latest` here to see if we can get away with it :)
=> chore(ci): use latest ubuntu to fix GH actions

src/elm/Pages/Build/History.elm
Related Issue: https://github.com/go-vela/community/issues/310
Add PR # + Description, and Tag # along with author to history hover card.
This is more inline with the details available on the list of builds screen.
=> feat: improve build summary

src/elm/Pages/Home.elm
Related Issue: closes https://github.com/go-vela/community/issues/409
Clicking the name of the Org will take the user to the org page, clicking the Chevron or anywhere else on the header will collapse / expand as it always has.
=> feat: Add link to the org page from home page

src/elm/Alerts.elm, src/elm/Api.elm, src/elm/Crumbs.elm, src/elm/Errors.elm, src/elm/Help/Commands.elm, src/elm/Help/View.elm, src/elm/Main.elm, src/elm/Nav.elm, src/elm/Pages.elm, src/elm/Pages/Build/History.elm, src/elm/Pages/Build/Model.elm, src/elm/Pages/Build/View.elm, src/elm/Pages/Builds.elm, src/elm/Pages/Deployments/Form.elm, src/elm/Pages/Deployments/Model.elm, src/elm/Pages/Deployments/View.elm, src/elm/Pages/Home.elm, src/elm/Pages/Hooks.elm, src/elm/Pages/Pipeline/Model.elm, src/elm/Pages/Pipeline/View.elm, src/elm/Pages/RepoSettings.elm, src/elm/Pages/Secrets/Model.elm, src/elm/Pages/Secrets/View.elm, src/elm/Pages/SourceRepos.elm, src/elm/Util.elm, src/elm/Vela.elm
simply going through and removing unused bits with help from [elm-review-unused](https://github.com/jfmengels/elm-review-unused).
if there's any strong feelings for any of it to be kept, feel free to comment.
=> refactor: remove unused

.env.example, DOCS.md, docker-compose.yml
Related to https://github.com/go-vela/server/pull/536
This updates any references of `SOURCE_*` -> `SCM_*` based off the above change.
=> fix: local setup with server

docker-compose.yml
quality of life tweaks for docker-compose.yml
following changes from 
- https://github.com/go-vela/server/pull/540
- https://github.com/go-vela/server/commit/fa0d72c3e1da98d3127bcc04c5a549e71d6aff4f#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R40-R41
- https://github.com/go-vela/server/pull/235
=> enhancement(queue): don't inject default route

src/elm/Pages/Build/View.elm, src/scss/_main.scss
adding a width/height wrapper in conjunction with `overflow-x: clip` to cause only the animation particles to get hidden when leaving the build-container
also, `z-index: 9999` on the actions menu to place it in front of the svg "particles"
=> fix: actions menu and build animation overflow bug

elm.json
used `npx elm-json upgrade` to bump some elm dependencies:
https://github.com/NoRedInk/elm-json-decode-pipeline/compare/1.0.0..1.0.1
https://github.com/elm-community/list-extra/compare/8.3.0..8.5.2
https://github.com/elm-community/maybe-extra/compare/5.2.1..5.3.0
see a few perf enhancements in the mix 🥳
=> chore: bump elm deps

src/elm/Main.elm, src/elm/Pages/Build/History.elm, src/elm/Pages/Build/View.elm, src/scss/_main.scss
The first fix is an issue introduced in v0.13.0-rc. The timestamp addition grew the filter bar vertically and started really hugging the list controls. Fix was to move margins from previous sole filter component to wrapper container that was added.
before:
after:
The second fix is for the recent build widget that has been there for a few versions. The text was not aligned on the left side - neither was the first item (if it was active). Also reduced distance between items slightly to match line weight used throughout.
before:
after:
Also removing some unused imports.
=> fix: a couple of UI fixes

.github/workflows/ci.yml, .github/workflows/release.yml, package.json
update builds to happen with node version defined in `.nvmrc`, also update package.json to bump `engine`. also busting cache due to build issues.
=> chore: bump node version in CI

.github/workflows/ci.yml, .github/workflows/release.yml
we never properly cached elm dependencies. this should do the trick and help avoid future issues with dependency resolution.
related: https://twitter.com/tgummerer/status/1488493440103030787
=> chore(ci): fix elm caching

.github/workflows/ci.yml, .github/workflows/release.yml, package.json
bumps node version to keep in line with https://github.com/go-vela/ui/pull/511
also simplifies Github Actions flow to pull node version from nvmrc in root of project instead of defining separately in each action
=> chore(node): bump node and simplify ci

src/elm/Pages/Secrets/View.elm, src/elm/Vela.elm
This PR is for part 1 of https://github.com/go-vela/community/issues/516
Adds the key column. to repo, org, and shared secrets tables
=> feat: add key to secrets tables

.postcssrc.json, package-lock.json, package.json
removes redundant, direct autoprefixer dependency as parcel2 deals with that under the hood and currently prints a warning in the console,
also upgrades a few transitive deps for vulns via `npm audit fix`
=> fix(deps): remove autoprefixer and npm audit fix

src/elm/Crumbs.elm, src/elm/Help/Commands.elm, src/elm/Main.elm, src/elm/Pages.elm, src/elm/Pages/Pipeline/Model.elm, src/elm/Routes.elm, src/elm/Vela.elm
this is part of the effort for https://github.com/go-vela/community/issues/587
removing the "Pipeline" page completely
it no longer matches the api spec which directly correlates a "pipeline" to a "build".
https://github.com/go-vela/community/issues/460
it also prepares for https://github.com/go-vela/ui/pull/551 which refines the pipeline url + pipeline tabs into a better experience
=> chore: remove Pipeline page

src/elm/Main.elm
these small typos are causing some cypress issues where page/tab loading is causing repo model to get overwritten
=> fix: typo in reposubpage loading

src/elm/Vela.elm
this field is being ignored by the server, but incoming changes may alter that.
removing it.
=> fix: remove trusted flag from default repo enable

src/elm/Vela.elm
Let the server set the default repo events to take advantage of the code added within https://github.com/go-vela/server/pull/758.
xref: https://github.com/go-vela/community/issues/745
=> enhance: utilize default repo events from api

.stylelintrc.js, package-lock.json, package.json
this PR updates stylelint to `v15` which involves the following changes:
- removed stylistic rules that will be deprecated in the next version of stylelint
- removes the dependency `stylelint-config-prettier` which is no longer needed because we already use `prettier`
see: https://www.npmjs.com/package/stylelint-config-prettier
and: https://stylelint.io/migration-guide/to-15/#deprecated-stylistic-rules
=> chore: upgrade stylelint to v15 and remove deprecated prettier rules

cypress/integration/hooks.spec.js, cypress/integration/secrets.spec.js, src/elm/Main.elm, src/elm/Pages/Hooks.elm, src/elm/Pages/Secrets/View.elm, src/elm/Table.elm
closes https://github.com/go-vela/community/issues/571
this aims to slightly improve the experience with some of the resource tables
- removes the toasty popup on secrets errors, unless they are a 500 server error.
- moves error message into the normal tables
- moves loading spinner into the normal tables
- adds some status code context to the error message
- applies the same changes to the hooks tables, for consistency!
loading:
401 example:
loading:
401 error example:
=> enhance: improve tables error/loading experience

src/elm/Main.elm
see title
fixes a bug where clicking "Redeploy" or getting redirected to the Promote Deployment page (redeploy) would not fetch the deployment nor would it pre-populate with the deployment we already have available.
closes https://github.com/go-vela/community/issues/725
=> fix(deployments): fetch deployment when tab switching to PromoteDeployment page

src/elm/Main.elm
see title
its the same refresh code, just ran on all tabs instead of just the build tab
closes https://github.com/go-vela/community/issues/553
=> fix(build): update favicon for all build tabs

src/elm/Pages/Build/View.elm
fixes an issue where a build has no `started` but it has a `finished` (errors)
looks like this now
=> fix(build): handle runtime for build.started == 0

src/elm/Crumbs.elm, src/elm/Help/Commands.elm, src/elm/Main.elm, src/elm/Pages.elm, src/elm/Routes.elm
see title, this adds a route shortcut `/org/repo/builds/pulls` for easily viewing only pull request builds.
its basically a shortcut to using `?event=pull_request`  
the idea came from the ease of moving between the SCM and a hosted vela instance. 
if this gets approvals, i will most likely add `/tags` and `/deployments` 
_**Note:**_ it is adding a "reserved route"
=> feat: adding /pulls shortcut route for viewing pull_request builds

docker-compose.yml, src/elm/Nav.elm
Closes https://github.com/go-vela/community/issues/485
Dependent on https://github.com/go-vela/server/pull/840 and https://github.com/go-vela/worker/pull/472
=> enhance(build): add cancel button for pending builds

cypress/integration/builds.spec.js, src/elm/Crumbs.elm, src/elm/Help/Commands.elm, src/elm/Main.elm, src/elm/Pages.elm, src/elm/Routes.elm
see: https://github.com/go-vela/ui/pull/656
same change, but for tag event
this adds a route shortcut `/org/repo/builds/tags` for easily viewing only tag builds.
its basically a shortcut to using `?event=tag`
i find myself swapping between github and vela, and like the convenience of being able to swap the host and like when the vela url matches with filtered content.
_**Note:**_ it is adding a "reserved route"
=> feat: adding /tags shortcut route for viewing tag builds

cypress/integration/crumbs.spec.js, src/elm/Crumbs.elm
with this change, if you're viewing secrets, the crumbs can redirect you back to secrets (for org,repo respectively)
the `Org` and `Repo` crumbs will now _*always*_ link to the org repos, and repo builds pages.
it also makes the usage of "Secret" > "Add" and "Schedule" > "Add" more consistent by making the crumbs display the resource if you're not viewing a repo tab
which matches the others more consistently now
=> fix: crumb link consistency

src/elm/Main.elm, src/elm/Pages/Deployments/View.elm
just removing some duplicate code, trying to clean things up
=> refactor: remove unused helper function

src/elm/Pages/Build/View.elm, src/elm/Pages/Schedules/Form.elm, src/elm/Pages/Schedules/Update.elm, src/elm/Pages/Schedules/View.elm
=> fix: simplify and remove unused

src/elm/Main.elm
this fixes a "Login Page" blip when you refresh the browser
it adds a boolean to track when a page is loading for the first time without an auth redirect, and skips the redirect to `Pages.Login` until `TokenResponse` can flip the boolean to `False`.  
it retains all of the current functionality since when the user is unauthenticated, for example if the cookies are cleared, or the token in cookies expires, token refresh will fail and cause the Login page redirect.
https://github.com/go-vela/ui/assets/48764154/7bc5595f-2635-4517-9996-914377196f5a
https://github.com/go-vela/ui/assets/48764154/6e0a9a8a-b32f-4002-90d4-9297253ca2e7
=> fix: login blip when refreshing a page

src/elm/Vela.elm
Calls to enable/disable an existing schedule in the UI do not work because the payload is encoded as `enabled: bool` rather than `active: bool`.
=> fix(schedules): correct encoding of update schedule payload for active field

src/elm/Main.elm
fixes a bug where adding a couple schedules in succession would confuse the redirects and toasties wouldnt appear.
- removes the redirect from Schedules "Add" and "Update" response, as it should only redirect back to the table on Delete.
- improves the messaging with schedules toasties
=> fix: apply consistent redirect and toasty logic for schedules

Dockerfile, Dockerfile.local
While we figure out how to stop renovate from suggesting we pin `docker-compose` service images, this will address https://github.com/go-vela/ui/pull/705 for now
=> chore(deps): pin nginx image in Dockerfile

src/elm/Main.elm
fixes a regression introduced by https://github.com/go-vela/ui/pull/642
two changes:
- return `False` when the resource is `NotAsked` to avoid refreshing in scenarios where the user hasnt looked at a tab yet.
- use the current `page` to check only the relevant resource in scenarios where the user has changed tabs.
=> fix: improve shouldRefresh logic for steps/services

src/elm/Pages/Build/History.elm, src/elm/Pages/Schedules/View.elm, src/elm/Util.elm
see title. it could be added as hover, but i think for last updated timestamps and other audit-fields similar to that should just render as the full timestamp.
examples:
=> fix(schedules): add precise date+time to last_updated and last_scheduled

cypress/integration/secrets.spec.js, src/elm/Main.elm, src/elm/Pages/Secrets/Form.elm, src/elm/Pages/Secrets/Model.elm, src/elm/Pages/Secrets/View.elm
Preparing patch release for v0.21.1 with these changes: https://github.com/go-vela/ui/pull/718
=> patch(v0.21.1/secrets): allow schedules for secret form if on allowlist

src/elm/Main.elm, src/elm/Pages/Deployments/Update.elm, src/elm/Pages/Deployments/View.elm
Ref: https://github.com/go-vela/cli/pull/480 and https://github.com/go-vela/server/pull/961
=> enhance(deployments): use scm default for target and adjust ref resolution

src/elm/SvgBuilder.elm, src/scss/_table.scss
just a small enhancement on top of the awesome work in https://github.com/go-vela/ui/pull/732
before:
after:
=> enhance(audit): use established skip styling

src/scss/_graph.scss
fixes an issue where single row graphs werent flexing to fill the container.
this does that and applies overflow hidden to the container
=> fix(viz): flex style and overflow for small graphs

cypress/fixtures/build_canceled.json, cypress/integration/build.spec.js, src/elm/Pages/Build/View.elm
small pr to improve message labeling for cancel events. canceled builds will either get a `canceled:` or `auto canceled:` message label.
also prefixes `#` to the build link for increased click area, especially for single digit builds. 
example for "auto canceled" status:
before:
after:
also spent some time to look at "autocanceled" vs "auto canceled" vs "auto-canceled", the latter of which i prefer most but there seems to be no concrete rules around this, so i left it as-is (and it avoids having to update the server component that returns the actual error message).
=> enhance(cancel): improve msg label for cancel events

src/scss/_graph.scss
removing flex and applying overflow visible.
this keeps the root graph correctly centered, while still applying the intended purpose of #738
=> fix(viz): apply overflow visible to root

cypress/fixtures/build_graph.json, src/elm/Main.elm, src/elm/Pages/Build/Graph/DOT.elm, src/elm/Pages/Build/Graph/Interop.elm, src/elm/Vela.elm, src/static/graph.ts, src/static/index.d.ts, src/static/index.ts
more stability for the elm vs. js render race condition, where the page root doesnt render quick enough for the graph render dispatch
also 
- renames `isRefreshDraw` to `sameBuild` to make it a bit clearer
- renames `centerOnDraw` to `freshDraw` to make it a bit clearer
=> fix(viz): track draw state to apply recenter on fresh draws

src/elm/Main.elm
fixes the following issue:
1. hard load graph page
1. click on step link
1. unexpand the step log on the resulting page (or expand any other step)
1. 400 error because build number was missing in request
this fix makes sure the buildNumber field is populated when you enter the site on a graph page
=> fix(graph): populate buildnumber on model

src/elm/Main.elm, src/elm/Pages/Deployments/View.elm, src/elm/Pages/Schedules/Form.elm, src/elm/Vela.elm
This story is attached to this PR: [https://github.com/go-vela/server/pull/1031](https://github.com/go-vela/server/pull/1031)
In switching over from pulling in deployments information from the SCM to pulling in from our own database, a few changes were made in the ui to allow this to happen.
As well, an ID column and builds column were added to the deployments table to better help users comprehend and use deployments.
=> feat(deployments): updating ui to show new changes to database

src/elm/Main.elm, src/elm/Pages/Deployments/View.elm, src/elm/Vela.elm
Removing the ID field because it doesn't really provide any useful data.
Adding the Created At field so that users can see when deployments were created.
Going from:
to:
=> fix: removing id field and adding created at field to deployments table

src/elm/Nav.elm
Trying to make less red appear on the page when it's business as usual. Would be open to maybe a white dot as an alert?
=> fix(tabs): remove red alert from audit on skipped hooks

src/elm/Pages/Deployments/View.elm
fixes a styling issue in light mode on the deployments page (see erroneous white lines).
before
after
also tested when the column was populated with builds, fwiw
=> fix(deployments): remove unnecessary class

src/elm/Pages/Org_/Repo_/Build_.elm
refactor regression: stages missing steps sort
=> fix: reversed stage steps via sort

src/elm/Pages/Org_.elm
fixes this ux regression with floating disabled pagination
=> fix(org): hide pagination when there are no org repos

src/elm/Layouts/Default.elm, src/elm/Layouts/Default/Org.elm, src/elm/Layouts/Default/Repo.elm
we need to reset the favicon in all layouts.
fixes situations where default init is not called and the favicon doesnt reset.
=> fix: reset favicon in nested layouts

src/elm/Vela.elm
fixes a regression introduced by scrubbing certain fields from the repo owner 
also please see: https://github.com/go-vela/server/pull/1113
=> fix: set repo.owner.admin to optional

src/elm/Pages/Org_/Repo_/Settings.elm
Closes https://github.com/go-vela/community/issues/69
Mock:
=> enhance(repo-settings): display repository owner in UI

cypress/fixtures/schedules.json, cypress/integration/schedules.spec.js, src/elm/Pages/Org_/Repo_/Hooks.elm, src/elm/Pages/Org_/Repo_/Schedules.elm, src/elm/Vela.elm
Whenever a user has a YAML bug in their pipeline, or any other build-breaking error that short-circuits pipeline execution, they can usually find these error in the Audit tab, where we populate the hook with the error message.
This is currently not available for schedules. Instead, the error is just logged.
https://github.com/go-vela/community/issues/872
=> feat(schedule)!: show schedule errors and nest object

src/elm/Layouts/Default.elm, src/elm/Pages/Dashboards/Dashboard_.elm
this is a more inclusive fix for the problem in #804
=> fix: restore favicon in Default layout, for all pages

src/elm/Pages/Org_/Repo_/Build_.elm, src/elm/Pages/Org_/Repo_/Build_/Services.elm, src/elm/Utils/Helpers.elm
while testing #810 i noticed that logs are called twice when you click on a step/service header, this is unintended side effect of tracking `OnHashChanged` events and using that to fetch logs without an extra check
does not impact refreshes, but still better than doing double calls for no reason.
=> fix: stop double log fetch on steps/services

.env.example, docker-entrypoint.sh, src/elm/Pages/Admin/Settings.elm, src/elm/Shared.elm, src/elm/Shared/Model.elm, src/static/index.d.ts, src/static/index.ts
i knew this would come back to bite. we tried updating it LIVE to 20k but had to use the API.
this PR bumps the default limit to `99999` and also adds `VELA_MAX_STARLARK_EXEC_LIMIT` as an available variable to allow this to be decreased or increased based on how admins have their server installed.
=> fix: allow starlark limit to be customized

cypress/fixtures/deployments_5.json, cypress/integration/deployment.spec.js, src/elm/Pages/Org_/Repo_/Deployments.elm
rendering `payload.parameters` as a list item cell in the deployments table
=> enhance: add payload.parameters to deployments table

src/elm/Pages/Org_/Repo_/Build_/Graph.elm
fetch the graph when the user directly asks for it, even if the build is already complete.
closes https://github.com/go-vela/community/issues/1003
=> fix(viz): always fetch graph when clicking refresh

cypress/fixtures/user_dashboards.json, cypress/integration/dashboards.spec.js, src/elm/Api/Endpoint.elm, src/elm/Api/Operations.elm, src/elm/Effect.elm, src/elm/Layouts/Default/Org.elm, src/elm/Pages/Dashboards.elm, src/elm/Pages/Dashboards/Dashboard_.elm, src/elm/Pages/Home_.elm, src/elm/Vela.elm, src/scss/_dashboards.scss
(description by David M)
replaces the static page on `/dashboards` page to show a list of the current user's dashboards that you can navigate to. it also lists repos assigned to each dashboard and last build status for each assigned repo.
this is an incremental improvement as we explore how to evolve dashboards and gather more feedback.
Updated static page when you don't have dashboards:
Same page when you have added a dashboard:
the dashboard id is a bit faint and really only shown because it's useful to use in CLI commands. whatever the post-beta version looks like, i imagine it won't show at all. it's also not super accessible in this format.
=> enhance(dashboards): show user's dashboards

src/elm/Pages/Dashboards.elm
see https://github.com/go-vela/server/pull/1193
also updates emoji for dashboards without any repos to ℹ️ instead of ⚠️
=> fix(dashboards): show appropriate messaging for deleted dashboards

cypress/integration/status_workers.spec.js, src/elm/Components/Tabs.elm, src/elm/Main.elm, src/elm/Main/Pages/Model.elm, src/elm/Main/Pages/Msg.elm, src/elm/Pages/Status/Workers.elm, src/elm/Route/Path.elm
this was behind admin page before, but the endpoint doesn't require
special perms. this moves it from /admin/workers to /status/workers.
"status" is a reserved word at the org level (for
GitHub), so it shouldn't cause an issue.
=> fix: move worker status

src/elm/Components/BarChart.elm
in some cases, the data is able to cause formatting for labels on the y axis to get clipped. the tick labels should have room now for 4 digits plus 1 decimal digit. also, the minimum max value on the y axis was changed to be 1 if driven by dataset.
=> fix(barchart): adjust y axis formatting

src/elm/Components/BarChart.elm
addresses a small rendering bug on the insights tab. i had moved over the axis rendering to allow for more room for labels, but didn't take care of the bar rendering 😱 
before:
after:
=> fix(barchart): fix render by incorporating offset

cypress/integration/status_workers.spec.js, src/elm/Pages/Status/Workers.elm
Was thinking it would be nice to be able to see the repo that is running the build in the workers table rather than just the build number
=> enhance(workers): render a more descriptive build link

cypress/fixtures/settings.json, cypress/fixtures/settings_updated.json, cypress/integration/admin_settings.spec.js, src/elm/Pages/Admin/Settings.elm, src/elm/Vela.elm
Follow up from https://github.com/go-vela/server/pull/1303
There isn't a max for the max enforced by the code base since it's an admin field. I did add 0-100 limits though. You could theoretically get around this using the API, so I figured it's ok. Not sure why any platform admin would set this higher.
=> feat(admin): add max dashboard repos to platform settings page

.github/renovate.json
follow-up to https://github.com/go-vela/ui/pull/865. noticed that the elm.json file (or the regex matcher) wasn't picked up on the dependency dashboard and used the `renovate` CLI to validate that i needed to surround the regex with "/" for it to get picked up properly.
=> fix(ci/renovate): add proper regex delimiter

.github/renovate.json
AI Generated Description:
This pull request adds a new configuration to the Renovate bot setup to group updates for Elm dependencies together. This will help keep Elm-related updates organized in a single pull request.
Dependency management:
* [`.github/renovate.json`](diffhunk://#diff-f82f7d36a61d22f640c25bdb8b0435bf9cb38679d99d5f460753fa668ee7cdb3R27-R30): Added a new rule to group updates for packages defined in `elm.json` under the group name "elm".
=> chore(ci): separate elm deps into own PRs

cypress/fixtures/build_approved.json, cypress/fixtures/build_canceled.json, cypress/fixtures/build_error.json, cypress/fixtures/build_failure.json, cypress/fixtures/build_graph.json, cypress/fixtures/build_pending.json, cypress/fixtures/build_pending_approval.json, cypress/fixtures/build_running.json, cypress/fixtures/build_success.json, cypress/fixtures/builds_10a.json, cypress/fixtures/builds_10b.json, cypress/fixtures/builds_5.json, cypress/fixtures/builds_50.json, cypress/fixtures/builds_all.json, cypress/fixtures/builds_comment.json, cypress/fixtures/builds_pull.json, cypress/fixtures/builds_push.json, cypress/fixtures/builds_schedule.json, cypress/fixtures/builds_tag.json, cypress/fixtures/settings.json, cypress/fixtures/settings_updated.json, cypress/integration/admin_settings.spec.js, cypress/integration/build.spec.js, src/elm/Components/RecentBuilds.elm, src/elm/Pages/Admin/Settings.elm, src/elm/Vela.elm, tests/BuildMetricsTest.elm
backport #858; due to https://github.com/go-vela/server/releases/tag/v0.26.5, https://github.com/go-vela/server/pull/1350 in particular
=> fix: backport PR #858
